name: Publish Hub

permissions: read-all

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch, tag or SHA to checkout"
        required: true
        type: string
        default: "main"

jobs:
  publish:
    uses: infinyon/fluvio/.github/workflows/connector-publish.yml@master
    with:
      package-name: http-source
      branch: ${{ github.event.inputs.branch }}
      fail-fast: false
      readme: ./README.md
    secrets:
      CLOUD_USER_EMAIL: ${{ secrets.ORG_HUB_SA_NAME }}
      CLOUD_USER_PASSWORD: ${{ secrets.ORG_HUB_SA_PASSWD_PROD }}
